name: Reusable Build Dependencies
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  workflow_call:
    inputs:
      bpb:
        description: build bpb
        type: boolean
        default: true
        required: false
      qpSWIFT:
        description: build qpSWIFT
        type: boolean
        default: true
        required: false
jobs:
  build_and_cache_venv:
    runs-on: ubuntu-24.04
    steps:
      - name: load venv
        id: load-venv
        uses: actions/cache@v3
        with:
          path: ~/venv
          key: venv
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          path: 'giskardpy'
          repository: SemRoCo/giskardpy
          ref: giskard_library
      - if: ${{ steps.load-venv.outputs.cache-hit != 'true' }}
        name: create venv
        run: |
          python3 -m venv ~/venv
          source ~/venv/bin/activate
          python3 -m pip install --upgrade pip
          pip3 install -r giskardpy/requirements.txt
          pip3 install -r requirements.txt
          cd giskardpy
          pip3 install .
      - if: ${{ steps.load-venv.outputs.cache-hit != 'true' }}
        name: cache venv
        id: cache-venv
        uses: actions/cache/save@v3
        with:
          path: ~/venv
          key: venv
      - if: ${{ (always()) && (runner.debug == '1') }}
        name: Setup upterm session
        uses: lhotari/action-upterm@v1
  build_and_cache_bpb:
    runs-on: ubuntu-24.04
    steps:
      - name: load venv
        id: load-venv
        uses: actions/cache@v3
        with:
          path: venv
          key: venv
      - name: load bpb
        id: load-bpb
        uses: actions/cache@v3
        with:
          path: ~/bpb
          key: bpb
      - if: ${{ steps.load-bpb.outputs.cache-hit != 'true' }}
        name: install pybullet
        run: |
          source ~/venv/bin/activate
          mkdir -p ~/bpb
          cd ~/bpb
          git clone https://github.com/SemRoCo/bullet3.git jazzy
          cd bullet3
          ./build_better_pybullet.sh
      - if: ${{ steps.load-bpb.outputs.cache-hit != 'true' }}
        name: cache bpb
        id: cache-bpb
        uses: actions/cache/save@v3
        with:
          path: ~/bpb
          key: bpb
      - if: ${{ (always()) && (runner.debug == '1') }}
        name: Setup upterm session
        uses: lhotari/action-upterm@v1
  build_and_cache_qpSWIFT:
    runs-on: ubuntu-24.04
    steps:
      - name: load venv
        id: load-venv
        uses: actions/cache@v3
        with:
          path: venv
          key: venv
      - name: load qpSWIFT
        id: load-qpSWIFT
        uses: actions/cache@v3
        with:
          path: ~/qpSWIFT
          key: qpSWIFT
      - if: ${{ steps.load-qpSWIFT.outputs.cache-hit != 'true' }}
        name: compile qpSWIFT
        run: |
          source ~/venv/bin/activate
          cd ~
          git clone https://github.com/qpSWIFT/qpSWIFT
          cd qpSWIFT
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          sudo cmake --build build --target install
      - if: ${{ steps.load-qpSWIFT.outputs.cache-hit != 'true' }}
        name: cache qpSWIFT
        id: cache-qpSWIFT
        uses: actions/cache/save@v3
        with:
          path: ~/qpSWIFT
          key: qpSWIFT
      - if: ${{ (always()) && (runner.debug == '1') }}
        name: Setup upterm session
        uses: lhotari/action-upterm@v1
#  create_pip_cache:
#    runs-on: ubuntu-24.04
#    steps:
#      - uses: actions/checkout@v3
#      - name: load pip cache
#        id: pip-load
#        uses: actions/cache@v3
#        with:
#          path: ~/.cache/pip
#          key: pip
#      - if: ${{ steps.pip-load.outputs.cache-hit != 'true' }}
#        name: install pip requirements
#        run: |
#          sudo apt install libeigen3-dev
#          python3 -m pip install --upgrade pip
#          pip3 install -r requirements.txt
#      - if: ${{ steps.pip-load.outputs.cache-hit != 'true' }}
#        name: cache pip
#        id: cache-pip
#        uses: actions/cache/save@v3
#        with:
#          path: ~/.cache/pip
#          key: pip
#      - if: ${{ (always()) && (runner.debug == '1') }}
#        name: Setup upterm session
#        uses: lhotari/action-upterm@v1
